// GENERATED by gen_bp_programs.py -- do not edit

localparam int BP_DONE_WORD = 63;   // dmem word the epilogue writes

typedef struct {
    string       name;
    string       hex;
    int          chk_reg;
    logic [31:0] chk_val;
} bp_scn_t;

localparam int BP_N_SCN = 5;

bp_scn_t bp_scn [BP_N_SCN] = '{
    '{ "loop_simple", "bp_loop_simple.hex", 2, 32'd600 },
    '{ "loop_nested", "bp_loop_nested.hex", 2, 32'd200 },
    '{ "correlated", "bp_correlated.hex", 9, 32'd1100 },
    '{ "pattern4", "bp_pattern4.hex", 9, 32'd100 },
    '{ "aliasing", "bp_aliasing.hex", 9, 32'd2500 }
};
